=== emilianohg/validacion-xml/example-xml/Blog.dtd
<!ELEMENT blog (authors, posts)>
<!ELEMENT authors (author*)>
<!ELEMENT posts (post*)>
<!ELEMENT author (name, email)>
<!ATTLIST author id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT post (title, poster, tags?, content, owner)>
<!ATTLIST post status (publish|draft) #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT poster (source+)>
<!ELEMENT source EMPTY>
<!ATTLIST source src CDATA #REQUIRED device (desktop|mobile|tablet) #IMPLIED>
<!ELEMENT content (#PCDATA)>
<!ELEMENT tags (tag+)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT owner EMPTY>
<!ATTLIST owner id IDREFS #REQUIRED>

=== emilianohg/validacion-xml/Blog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE blog SYSTEM "Blog.dtd">
<blog>
    <authors>
        <author id="emilianohg">
            <name>Emiliano Hern√°ndez Guerrero</name>
            <email>emilianohg@example.com</email>
        </author>
        <author id="efra">
            <name>Efrain Amarillas</name>
            <email>efra@example.com</email>
        </author>
        <author id="gerry">
            <name>Luis Gerardo Aguilar</name>
            <email>gerry@example.com</email>
        </author>
    </authors>
    <posts>
        <post status="publish">
            <title>Titulo 1</title>
            <poster>
                <source src="http://www.example.com/images/poster-desktop.jpg" device="desktop"/>
                <source src="http://www.example.com/images/poster-mobile.jpg" device="mobile"/>
                <source src="http://www.example.com/images/poster.jpg"/>
            </poster>
            <tags>
                <tag>lorem</tag>
                <tag>ipsum</tag>
            </tags>
            <content>Lorem ipsum dolor sit amet...</content>
            <owner id="emilianohg"/>
        </post>
        <post status="draft">
            <title>Titulo 2</title>
            <poster>
                <source src="http://www.example.com/images/poster.jpg"/>
            </poster>
            <content>Lorem ipsum dolor sit amet...</content>
            <owner id="gerry"/>
        </post>
    </posts>
</blog>

=== emilianohg/validacion-xml/example-xml/Blog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE blog SYSTEM "Blog.dtd">
<blog>
    <authors>
        <author id="emilianohg">
            <name>Emiliano Hern√°ndez Guerrero</name>
            <email>emilianohg@example.com</email>
        </author>
        <author id="efra">
            <name>Efrain Amarillas</name>
            <email>efra@example.com</email>
        </author>
        <author id="gerry">
            <name>Luis Gerardo Aguilar</name>
            <email>gerry@example.com</email>
        </author>
    </authors>
    <posts>
        <post status="publish">
            <title>Titulo 1</title>
            <poster>
                <source device="desktop">http://www.example.com/images/poster-desktop.jpg</source>
                <source device="mobile">http://www.example.com/images/poster-mobile.jpg</source>
                <source>http://www.example.com/images/poster.jpg</source>
            </poster>
            <tags>
                <tag>lorem</tag>
                <tag>ipsum</tag>
            </tags>
            <content>Lorem ipsum dolor sit amet...</content>
            <owner id="emilianohg"/>
        </post>
        <post status="draft">
            <title>Titulo 2</title>
            <poster>
                <source>http://www.example.com/images/poster.jpg</source>
            </poster>
            <content>Lorem ipsum dolor sit amet...</content>
            <owner id="gerry"/>
        </post>
    </posts>
</blog>
